apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-demo

resources:
  - namespace.yaml
  - 00-role.yaml
  - 00-account.yaml
  - 01-role-binding.yaml
  - 02-traefik.yaml
  - 02-traefik-services.yaml
  - 03-whoami.yaml
  - 03-whoami-services.yaml
  - 04-whoami-ingress.yaml